nome = input('Digite seu nome: ')
idade = int(input('Digite sua idade: '))
print()
num1 = input('Digite o primeiro número: ')
num2 = input('Digite o segundo número: ')
num1= float(num1)
num2= float(num2)
print()
print(f'Seu nome é {nome}')
print(f'Você tem {idade} de idade')
print(f'A soma dos números é igual a {num1 + num2}')